### PR TITLE
Add favicons

### PR DESCRIPTION
**Pull request by flochtililoch**
Used [Realfavicongenerator.net](https://realfavicongenerator.net/) to generate favicon, based on the remote icon used in [Open Source Universal Remote site](http://opensourceuniversalremote.com).

Here's how it looks on chrome:
chrome

and safari:
safari-pinned-tab

and iPhone:
iphone

### CODE REVIEW

**Comment by flochtililoch** [comment]
Will explore with more colors, then re-open

**Comment by flochtililoch** [comment]
Here are a few alternative:

screen shot 2016-01-10 at 11 27 11 am
screen shot 2016-01-10 at 11 27 19 am
screen shot 2016-01-10 at 11 27 45 am
screen shot 2016-01-10 at 11 27 58 am
screen shot 2016-01-10 at 11 30 32 am
screen shot 2016-01-10 at 11 30 38 am

Could either go with the initial submitted code (black icon, over white background for iOS), or make any adjustments per your suggestions, just let me know!

**Comment by OvisMaximus** [comment]
I like the blue on white version most. I'd wish the keys were not transparent, but also white. But all are great in comparison to my own experiments.

**Comment by flochtililoch** [comment]
@OvisMaximus thanks for spotting this detail! I've updated the remote image to have white-filled keys:

screen shot 2016-01-10 at 9 04 09 pm
screen shot 2016-01-10 at 9 04 16 pm
screen shot 2016-01-10 at 9 04 22 pm
screen shot 2016-01-10 at 9 04 54 pm

**Comment by alexbain** [comment]
This looks great. I think blue/white is a good combo to start - we can always tweak down the road.

Thanks for posting some screenshots in different platforms.

**Pull request merged**
