### PR TITLE
Implementation of GPIO control

### PR DESCRIPTION
**Pull request by OvisMaximus**
I extended the layout of the Raspbian-Pi IR board like this: https://upverter.com/OvisMaximus/108f556de56bd474/Raspi-HIFI-Control-Center/

and attached a relais board like that
http://www.amazon.de/Kanal-Relay-Relais-Module-Arduino/dp/B00AEIDWXK
which i integrated into a power plug connector.

The code changes in this pull request enable me to use lirc_web to control this stuff also with the same GUI

### CODE REVIEW

**Comment by alexbain** [comment]
Can you do an interactive rebase on this to squash down the commits? Also, there's a merge conflict so once you've squashed the commits you'll need to rebase against master.

**Comment by OvisMaximus** [comment]
As I understand this, this rebase is the tool to reorder and cleanup commits. since I resolved already the last collisions, it should be possible to do a auto merge. I just spent 90 minutes in performing this interactive rebase, doing tenths of merges I already did. Ending up in a source tree with 59 new introduced lint errors and some failing tests.

And even if I'd fix the mess, I'd have to force push the changes, what I don't like to do.

In the end it feels really odd to do this rebase, since I can't see the benefit. Would you help me here?

**Comment by OvisMaximus** [comment]
done :-)

**Comment by OvisMaximus** [comment]
Since the latest node update the build of wiring-pi fails. Is it possible to update the gcc version from 4.6.3 to 4.9.2 on travis so that travis uses the same version as raspbian?

see also https://github.com/eugeneware/wiring-pi/issues/33

**Comment by alexbain** [comment]
@OvisMaximus I got this working here:

https://travis-ci.org/alexbain/lirc_web/builds/102996397

Take a look at the `.travis.yml` file to see how to force it to use `gcc-4.9` and `g++-4.9`:

https://github.com/alexbain/lirc_web/blob/wiring-pi/.travis.yml

**Comment by OvisMaximus** [comment]
yay!

**Comment by alexbain** [comment]
What do you think about merging this into a `devices` or a `v2` branch instead of `master` while we finish thinking through how to handle multiple protocols? I'd like to get all of the http device and zwave device into a big shared branch so we can start brainstorming how to refactor.

**Comment by alexbain** [comment]
@pkubuat you might be interested in chiming in here, too

**Comment by OvisMaximus** [comment]
devices / v2 sounds really good. 
The changes to travis.yml did the job - awsome!

**Comment by OvisMaximus** [comment]
Setteling thoughts about V2: the different supported hardware (not only lirc anymore) makes it feel appropriate to switch to a new product (osur). The macro thing comes with breaking changes on the configuration side: V2 is the minimum change regarding semver.

regarding this patch, v1 master isnt the correct branch for this pull request, so I close it.

**Pull request closed without merging**
